### ISSUE TITLE
dx_pri and dy_pri unclear documentation

### ISSUE THREAD

**Issue by x94carbone** [ziatdinovmax/pyroVED#31]
https://github.com/ziatdinovmax/pyroVED/blob/185404796d00a2efe3063d6ab84b002496b7befd/pyroved/models/trvae.py#L123

What are these objects?

**Comment by ziatdinovmax** [comment]
@x94carbone Good catch. The dx_prior allows a user to pass their "belied" about a degree of translational disorder in the system. Practically, this is a coefficient between 0 and 1 by which we multiply our offset latent variable.

**Comment by x94carbone** [comment]
Interesting. Ok now that I have an idea I'll take a second look and see if I can document it a bit. I'm guessing everything is scaled to 1, hence the value being between 0 and 1? This would be consistent with the grids too. Thanks!

**Comment by ziatdinovmax** [comment]
Yes, the grid is defined in the (-1, 1) range. Basically, if you have an object in the center of an image then you don't want to move it (or more precisely, the grid, because we don't touch the actual data) by more than half of the image width/height. That's why we have to do a rescaling of the encoded offset latent variable at the prediction stage:
```python
rescale_coef = ((x.max() - x.min()) / 2 ) * svae.t_prior
z_mean[:, 0] * rescale_coef
```
